### ISSUE TITLE
Добавить атрибут action для кнопок Aqara и Xiaomi

### ISSUE THREAD

**Issue by tmks175** [u236/homed-service-common#4]
Переезжаю постепенно с z2m на Homed (gateway nano), настроен HA через autodiscovery. После добавления кнопок Aqara (WXKG11LM) и Xiaomi (WXKG01LM), думаю и любых других, логи (HA) быстро заполняют записи: 
`
Template variable warning: 'dict object' has no attribute 'action' when rendering '{{ value_json.action }}'
`
Стоит зайти на веб-интерфейс Homed или обновить его (F5), 3-4 записи сразу летит в лог HA.
Хотелось бы поправить этот атрибут, хотя бы для кнопок (как самых распространённых устройств в УД).

Версии: interface/web 2.3.6 | zigbee 3.8.3

**Comment by u236** [comment]
Я не пользуюсь HA и мне катастрофически сложно решать такие задачи. Из того что я смог нагуглить, вероятно может помочь добавление флага `is_defined` в темплейт `value_template` в дискавери топике, чтобы получилось `{{ value_json.action | is_defined }}`. Прошу проверить этот вариант в ручную, если поможет, добавлю в код.

**Comment by u236** [comment]
https://github.com/u236/homed-service-common/commit/3e4809224544b6393f3b1461fdd0b2edddfff1ee
